# Generated by Django 6.0.1 on 2026-03-04 08:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inscriptions', '0004_eleve_classe_reelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2nd', '2nde')], max_length=10)),
                ('type_eval', models.CharField(choices=[('DEVOIR', 'Devoir simple'), ('COMPOSITION', 'Composition / Examen')], max_length=20)),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')])),
                ('date_eval', models.DateField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppNote.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Inscriptions.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppNote.evaluation')),
            ],
            options={
                'unique_together': {('eleve', 'evaluation')},
            },
        ),
    ]
