# Generated by Django 6.0.1 on 2026-03-08 16:52

import Inscriptions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Scolarite_Affectation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('classe', models.CharField(choices=[('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2nd', '2nde')], max_length=10)),
                ('classe_reelle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Classe Affectée (ex: 6ème A)')),
                ('adresse', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Inscriptions.models.get_image, verbose_name="Photo d'identité")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pere_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du père')),
                ('pere_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom du père')),
                ('pere_profession', models.CharField(blank=True, max_length=100, verbose_name='Profession du père')),
                ('pere_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du père')),
                ('pere_adresse', models.TextField(blank=True, verbose_name='Adresse du père')),
                ('mere_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom de la mère')),
                ('mere_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom de la mère')),
                ('mere_profession', models.CharField(blank=True, max_length=100, verbose_name='Profession de la mère')),
                ('mere_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de la mère')),
                ('mere_adresse', models.TextField(blank=True, verbose_name='Adresse de la mère')),
                ('personne_prevenir_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('personne_prevenir_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('personne_prevenir_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('personne_prevenir_lien', models.CharField(blank=True, max_length=50, verbose_name="Lien avec l'élève")),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_naissance', models.FileField(upload_to=Inscriptions.models.document_upload_path)),
                ('last_bulletin', models.FileField(upload_to=Inscriptions.models.document_upload_path)),
                ('diplome', models.FileField(upload_to=Inscriptions.models.document_upload_path)),
                ('est_valide', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Inscriptions.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='Inscriptions.tuteur'),
        ),
    ]
