# Generated by Django 6.0.2 on 2026-03-03 13:30

import Inscriptions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ACTE', 'Acte de Naissance'), ('DIPLOME', 'Dernier Diplôme'), ('PHOTO', "Photo d'identité")], max_length=10)),
                ('fichier', models.FileField(upload_to=Inscriptions.models.document_upload_path)),
                ('est_valide', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Inscriptions.eleve')),
            ],
        ),
    ]
