# Generated by Django 6.0.2 on 2026-03-03 14:32

import Inscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenteleve',
            old_name='fichier',
            new_name='acte_naissance',
        ),
        migrations.RemoveField(
            model_name='documenteleve',
            name='type_document',
        ),
        migrations.AddField(
            model_name='documenteleve',
            name='diplome',
            field=models.FileField(default='', upload_to=Inscriptions.models.document_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenteleve',
            name='last_bulletin',
            field=models.FileField(default='', upload_to=Inscriptions.models.document_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.CharField(choices=[('6EME', '6ème'), ('5EME', '5ème'), ('4EME', '4ème'), ('3EME', '3ème'), ('2nd', '2nde')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
