# Generated by Django 6.0.2 on 2026-03-03 17:20

import Inscriptions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0002_rename_fichier_documenteleve_acte_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pere_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du père')),
                ('pere_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom du père')),
                ('pere_profession', models.CharField(blank=True, max_length=100, verbose_name='Profession du père')),
                ('pere_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du père')),
                ('pere_adresse', models.TextField(blank=True, verbose_name='Adresse du père')),
                ('mere_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom de la mère')),
                ('mere_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom de la mère')),
                ('mere_profession', models.CharField(blank=True, max_length=100, verbose_name='Profession de la mère')),
                ('mere_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de la mère')),
                ('mere_adresse', models.TextField(blank=True, verbose_name='Adresse de la mère')),
                ('personne_prevenir_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('personne_prevenir_prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('personne_prevenir_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('personne_prevenir_lien', models.CharField(blank=True, max_length=50, verbose_name="Lien avec l'élève")),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Inscriptions.models.get_image, verbose_name="Photo d'identité"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='Inscriptions.tuteur'),
        ),
    ]
