# Generated by Django 6.0.2 on 2026-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0003_tuteur_eleve_photo_eleve_tuteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe_reelle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Classe Affectée (ex: 6ème A)'),
        ),
    ]
